[env:rpipico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
platform_packages = 
    framework-arduino-pico @ https://github.com/earlephilhower/arduino-pico.git